### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ponypower** [TeamNewPipe/website#10]
**Let's build this website!**
Continuing the discussion from https://github.com/TeamNewPipe/NewPipe/issues/277 and https://github.com/TeamNewPipe/NewPipe/issues/435.

I went through a few dozen "best app websites" when I put together the new design and according to what I saw it looks like nearly everything has been figured out that could have been. So there are definitelly tons of cool ideas out there offering solutions for anything. We just gotta look for them.

@TobiGr Cool stuff. Looks like the resizing works pretty well. The site gotta be built around that mechanism for sure. Good job. The picture below shows the original idea what should happen when a feature is selected.
![weblap selected](https://cloud.githubusercontent.com/assets/16841860/23089007/eff123e0-f582-11e6-95ff-e2a22c51e936.jpg)

@theScrabi Could you list the main features you think would be important to mention on the website? 6-8 features for example, to people who are _a)_ unfamiliar with everything beyond the official youtube app and _b)_ using an other alternative youtube client app.

@nate2014jatc Nope, not yet, but coming soon.

I'm going to put together the desktop version of the new design today (saturday) and post it.

**Comment by TobiGr** [comment]
@ponypower that's a good idea.
I was thinking about a gallery that has a horizontal scrolling. By clicking on a feature the gallery would scroll to this slide. This would allow us to show some more specific pictures of the app and at the same time reduce the required space for small screens.
This is only a quick scratch. But if you like it, maybe we can figure out a better design.
![gallery overview](https://cloud.githubusercontent.com/assets/17365767/23092216/4653b11a-f5c6-11e6-98f0-90f918268d3e.png)
![gallery feature](https://cloud.githubusercontent.com/assets/17365767/23092215/464ea1e8-f5c6-11e6-930b-c7e508b8154d.png)

**Comment by TobiGr** [comment]
@ponypower Did you design the features' icons or did you use some from FontAwesome or somewhere else?

**Comment by ponypower** [comment]
I couldnt finish the design today, but here are some carefully placed rectangles for a FullHD screen. This is an extension of the mobile version so there should be no major issues with resizing. The other parts of the site are coming too with new ideas from @TobiGr. 

@TobiGr The feature icons are temporary designs. Downloading them is a good idea. Not much hassle and good quality stuff.
Placing screenshots next to the feature details would look fancy. But a gallery for each is maybe an overdo. One screenshot should do it for each. Maybe it's not even necessary to put there the whole phone template. A magnified crop of the screenshot could be even better with a stylish border or something.

![1920 weblap-01](https://cloud.githubusercontent.com/assets/16841860/23097452/80138aa6-f634-11e6-8feb-8d87295cf212.jpg)

**Comment by theScrabi** [comment]
I like the design with the squares :+1:

**Comment by TobiGr** [comment]
Good job. It's perfect!

**Comment by TobiGr** [comment]
@Ponypower we don't have to add one slide for each feature. I think that some things don't need an explanation (for example free, add free and lightweight).
But to show how the app works we need screenshots.

**Comment by TobiGr** [comment]
@ponypower Do you have any ideas for texts that describe the respective features in more detail? 
The text describing the background player sounds good 👍

**Comment by ponypower** [comment]
Giving a few witty lines to an obvious feature could be funny :) Btw I haven't put much thought into the feature details. I'm cool with someone else doing it. Try to give it a good vibe though.

Okay, we need screenshots. Someone please give me expressive shots of the functions in a common screen ratio. (My own screen is 480x800.)

**Comment by ponypower** [comment]
In the meanwhile I'm experimenting with the design. Trying to put together something cool. Expect some delay :(

**Comment by TobiGr** [comment]
No problem. I'm focusing on the gallery. I hope I can finish it by the end of the week.

**Comment by TobiGr** [comment]
@ponypower can you please upload the background image of the header so I can use it?

**Comment by ponypower** [comment]
I'm sorry, I got pretty busy the last two weeks but I'm expecting to get a decent design by the end of this week. *fingers crossed*

**Comment by TobiGr** [comment]
@theScrabi Do you want more information about the slides and the CCC to be displayed? And should we say CCC 2016 or 33C3?

![screenshot 5 full](https://cloud.githubusercontent.com/assets/17365767/24499698/cdbc4e6e-1542-11e7-9c7f-bd46d719e477.png)

**Comment by theScrabi** [comment]
I think a link to the slides would be enough.
I would write 33c3.

**Comment by TobiGr** [comment]
While fixing a problem, that the animation is loaded but not displayed on small screens, following question comes to my mind:
Should we load and display the animation on small devices / screens? 
Some devices / browsers (often the combination of both) are too slow for playing videos.

I'd prefer to display the animation frameless (without the Nexus image) on small devices. We can enable 'click and play' for small devices, so the video is only loaded when the user taps on it. It could look like this (will spend some time on a better design later):
![screenshot 6 small - with animation](https://cloud.githubusercontent.com/assets/17365767/24522615/651d8168-1590-11e7-9ffa-e8ca6b1e6d33.png)
But first, we need the new animation and screenshots from #13.
@theScrabi Is the link okay now?

**Comment by TheAssassin** [comment]
We don't really need to show an animation on small screens, to be honest.

**Comment by TobiGr** [comment]
Good. Than I'll add the script to prevent loading it on small screens. New PR or the current?

**Comment by TheAssassin** [comment]
I don't really mind, it's a bit messy already. I am going to have a detailed look at it whenever you say it's ready.
Looks better and better with every commit.

**Comment by TobiGr** [comment]
I made some changes, because the white background of the text containers was a little aggressive and the donate button didn't fit to the other colors. But ultimately I'm not happy with the donate button. Any suggestions?

![screenshot 7 full](https://cloud.githubusercontent.com/assets/17365767/24580874/99e88952-1710-11e7-9bcc-5278dc02e9b2.png)

**Comment by TobiGr** [comment]
That's my final design for small screens.
Final design for desktops see above. (I'm fine with the donate button now :) )
I hope you like it. If there are any things you'd like to change, please tell me!
![screenshot 8 small](https://cloud.githubusercontent.com/assets/17365767/24582769/5d186566-1737-11e7-8d51-3fd5254680ce.png)

**Comment by TobiGr** [comment]
I'm working on the CCC slides improving the design @TheAssassin worked out. I have to agree that the link to the slides should be at the bottom of the page. @theScrabi What about this instead of the extra container below the gallery?

![screenshot 10 full](https://cloud.githubusercontent.com/assets/17365767/25106028/b5ce0fc0-23c7-11e7-8949-9ef139660285.png)
![screenshot 10 small](https://cloud.githubusercontent.com/assets/17365767/25106029/b5d16972-23c7-11e7-9c08-f8a640c39f1c.png)
If you think this is better, I'll work out a better design for mobile too.
I improved the `background-color` of the `text-2` and `slides-container` as well, resulting in that:

![colors-6](https://cloud.githubusercontent.com/assets/17365767/25106064/e5231d60-23c7-11e7-9cf2-a8d4d4d507a7.png)

**Comment by TobiGr** [comment]
To be honest, I'm not happy with the gallery nor the popup to introduce NewPipe's features (popup see [here](https://github.com/TeamNewPipe/NewPipe/issues/277#issuecomment-216072533) and at the very beginning of this issue). Another idea for the features is an accordion, so only the content of the focused feature is visible while the other details are collapsed. When clicking on a different item it will expand and the previous focused one will collapse .
I'm not a friend of accordions on large screens, because they aren't good to handle with a cursor and sometimes look lost on large screens. But I think they are a really clever solution for mobiles.

What do you think of having a gallery for large and medium devices and an accordion for on small screens? (Btw a little more response than last time could be helpful).

This is how an accordion could look on mobile:
![screenshot 15 features](https://cloud.githubusercontent.com/assets/17365767/25673951/7fb2b23c-3039-11e7-8c51-7908e346698b.png)

**Comment by ponypower** [comment]
Hey guys, I'm back. I'm going to continue the work on the design where I left.
I can see @TobiGr is doing a pretty decent job.
Are you guys open to implement an improved design (which im planning to continue work on) or you want to go with the above version?

**Comment by TobiGr** [comment]
I prefer to continue with the stuff that's already implemented :wink: 
But maybe we both can work on an improved design together, discuss the issues that are left and embellish the current design.
Apart from this we need a concept that could be applied to the app later too.

**Comment by TheAssassin** [comment]
I agree, a second independent design seems like a lot of overhead. And @TobiGr has invested a notable amount of time already, so choosing a completely different theme is unlike to happen. I agree that you can by bundling your efforts you can create something awesome together. Collaboration is the foundation of the open source world, after all.

**Comment by TobiGr** [comment]
@ponypower Do you have any ideas on how to design the feutures so that they look good and can be easily handled on small and large screens?

**Comment by TobiGr** [comment]
@ponypower Can you please upload the header's background image you used [here](https://github.com/TeamNewPipe/website/issues/10#issuecomment-280881843) to the repository so I can work with it?

**Comment by TobiGr** [comment]
I have some general questions one some features and design tweaks of the new websites where I need your opinion.

## Search in navigation bar

![blog-navbar-search-1](https://user-images.githubusercontent.com/17365767/26994251-221c56d2-4d67-11e7-9062-429d2874b4db.png)
![blog-navbar-search-1-focus](https://user-images.githubusercontent.com/17365767/26994252-221e2cbe-4d67-11e7-8433-a88dbd198ae9.png)

@theScrabi @TheAssassin @ponypower  I have already included a search for all blog posts in the the navigation bar and the sidebar for all sites in /blog/. Should we included this search also in the navigation bar of the main page? Pro: We get more attention, people search and get to the blog where they can find more information about NewPipe and how to contribute. Contra: As long as we do not have enough articles a search is useless and our search is limited to posts. This is not good if people search for static sites and the content on it. The don't get a result but a matching page exists (I can try to change this, but this will need some time).

## Blog article on main page

@ponypower I'm not happy with that design for the article wich is placed on the main page. It looks quite big and heavy. Any ideas how to solve this? I tried brighter colors but they do not make the whole container look lighter.

![screenshot 25 full - blog - dark](https://user-images.githubusercontent.com/17365767/26994756-4aa34aaa-4d69-11e7-8a66-c61901fe26e6.png)
![screenshot 25 full - blog - light](https://user-images.githubusercontent.com/17365767/26994757-4aa37066-4d69-11e7-8fc9-935c3c6de9b2.png)

## Icon color

I didn't get feedback on [my post](https://github.com/TeamNewPipe/website/issues/10#issuecomment-298986887), so I assume that everbody is fine with a gallery. At the moment the icons in the gallery are red wich is a litte difficult because the whole header is red. That decreases the eye-cathing effect that the icons actually should have.
I'd like to darken the icons, but I'm not sure if that is the best solution. A different color could also be a solution. But I'm not even conviced that this is a real problem. I just want to know your opinion on this.

![screenshot 25 full - icon- red](https://user-images.githubusercontent.com/17365767/26994937-643c201c-4d6a-11e7-9110-e12cdb4ff779.png)
![screenshot 25 full - icon- dark](https://user-images.githubusercontent.com/17365767/26994936-64337980-4d6a-11e7-94f2-01f63ae89068.png)

**Comment by TheAssassin** [comment]
The more I think about it, the less important that "last article" on the main page gets, primarily because people actually have to scroll down all that page. Also, it seems like the cost-benefit ratio isn't acceptable, due to the high effort required to make it work and integrate nicely. Writing a Jekyll plugin just for _that_ thing?

I'd propose to just let the blog remain a separate component. Design doesn't necessarily have to match perfectly either. That greatly simplifies our efforts to build this website, and both instances can be maintained separately. Should be way less effort to implement it that way.

@TobiGr you've implemented it so far, I'd appreciate your opinion on that proposal.

**Comment by TobiGr** [comment]
If we remove the "latest article" box from our main page, we should find a way to tell the people that we have an active blog. Once some articles are published, they worth it to get attention.

The blog integration on the main page is not a problem with Jekyll as long as we keep both sites in the same repository. The question is if there is a clean and nice way to put the blog and all its components into a subdirectory. If we keep the blog and the website in different repositories - and that also makes sense - displaying the latest article will be a lot a work.


> The more I think about it, the less important that "last article" on the main page gets, primarily because people actually have to scroll down all that page

I understand the problem that people have to scroll down a lot to reach information about the blog. That is a big problem, on the other hand these people who are interested in NewPipe will stay a little on the main page to inform theirselfs. So basically we have three options:

1. move the `news` container above the `text-2` container (my favourite)
2. add some lines about the blog to the `text-1` container
3. highlight the blog link in the `navbar`

Moving the blog up, gives us two additional possible layouts:

1. keep the latest article and change the colors
2. replace the article with a full-width banner announcing the blog

All together I think the blog is too important to be not displayed in a nice way on the main page.

**Comment by TobiGr** [comment]
@TheAssassin The full-width banner can look like this:
![screenshot 26 full - semi](https://user-images.githubusercontent.com/17365767/27013045-3c63d3c8-4edc-11e7-845d-8f7be96ed09c.png)

**Comment by TheAssassin** [comment]
Looks good to me. I think this will suffice for now.

**Comment by theScrabi** [comment]
@TobiGr I don't know where or when, but I think you asked me once to look at your feature description. I think it's good the way it is :)

By the way, if we:
 - [ ] Changed the icons to the current version
 - [ ] and replaced the video

I would be ok to release the website. I mean we can still Improve it after the first version is released. @TheAssassin @TobiGr what do you thing?

**Comment by TheAssassin** [comment]
I am preparing to finally move to a new host. I'll schedule the release for when I'm done with that.

**Comment by TobiGr** [comment]
@theScrabi Do you have a .SVG file of the logo?

**Comment by theScrabi** [comment]
Yes.
The android materialized [icon](https://github.com/TeamNewPipe/NewPipe/blob/master/assets/new_pipe_icon_5.svg) and the [flat icon](https://github.com/TeamNewPipe/NewPipe/blob/master/assets/NP%20logo%20v2.svg).
This Icon should be replaced, since the icon shown on the website was never uses.

**Comment by theScrabi** [comment]
However nice work so far, I like the new website :+1:

**Comment by TheAssassin** [comment]
Auto deployment hasn't been set up yet, but we rarely update it so I'll leave it to manual updates for now.

**Comment by TobiGr** [comment]
I am quite busy right now but I hope to get everything done until Friday so @TheAssassin can put the website online at the weekend or whenever the server is ready.

**Comment by TheAssassin** [comment]
@TobiGr check it out, the website is live: https://newpipe.schabi.org

**Comment by TobiGr** [comment]
@TheAssassin When I try to visit https://newpipe.schabi.org I get either timeout or connection errors.

**Comment by TheAssassin** [comment]
That's really strange. My monitoring reports it to be up and running fine. I occasionally visit it, and don't experience any problems.

**Comment by TobiGr** [comment]
The errors are gone. I can visit it now.  Never mind.

**Comment by TobiGr** [comment]
@TheAssassin Some images and the animation are not in the Server (or at least the addresses are wrong)
```
img/feather.png
img/f-droid.svg
img/footage.webm
```

**Comment by TobiGr** [comment]
As I've said before, I'd like to change the way we show NewPipe's features.
My idea is to make as many as possible features visible and immediately accessible (using the right sidebar). At the same time we have the possibility to interact with the user. E.g we can have a first "dialog" which shows some facts (fast, small, minimal battery usage, mobile data friendly or whatever) about the app. To each fact we can add an animated progress bar, loading circles or something similar.
This new design has also quite big advantages for mobile devices and small screens: my idea is to only show the "sidebar". A tap on a feature could also trigger a swipe-to-left animation which hides the main page and shows the dialog.

@TheAssassin @theScrabi Do you have any other ideas how we  can improve the features? Do you see any disadvantages in the new concept?

The screenshot below is only a quick try to show you my ideas. The design will improve, but I am not sure whether we can keep the transparent background which makes our website look quite "light" at the moment.

![features-01](https://user-images.githubusercontent.com/17365767/34454408-2bd23058-ed6b-11e7-9c6a-f742a33b77ed.png)

**Comment by TheAssassin** [comment]
@TobiGr I love it. And I'll check the issue.

**Comment by theScrabi** [comment]
Yea its great :)

**Comment by theScrabi** [comment]
@TheAssassin btw whats with the video should we host it? Or should I upload it to some service?

**Comment by TheAssassin** [comment]
@theScrabi are you talking about the talk's video? Sure, I can host it, free/open services ftw. But as NewPipe is a YouTube app it might make sense to upload it there, too.

**Comment by theScrabi** [comment]
Yea ... maybe although I hate youtube :/

**Comment by TheAssassin** [comment]
@theScrabi I am not a fan of Google either, au contraire. That was more like a marketing idea.

@TobiGr I rebuilt the Docker container once again. Please check again. If it isn't working now, I'll have to dig a bit deeper.

**Comment by theScrabi** [comment]
@TheAssassin I uploaded it to YT, but I also took it down again. I absoloutly don't like it, I'd rather like to host it on media ccc self hosted or even vimeo.

**Comment by theScrabi** [comment]
We could put it on vimeo, or (and) host it on d.tube

**Comment by TheAssassin** [comment]
@theScrabi I'd assume media.ccc.de would help spreading the video most.

For inclusion on the website, I can host it as well, no need to have any external service track users.

**Comment by theScrabi** [comment]
All right :) Thats cool.

**Comment by TobiGr** [comment]
We should write a blog post to tell people that there's a video. 
@theScrabi Is it possible to pin https://github.com/TeamNewPipe/NewPipe/issues/935 to the top so more people visit our blog and read the posts? And that issue could also be a way to inform them about new posts.

@TheAssassin Thanks. The website is up to date.

**Comment by theScrabi** [comment]
I think the best was to add a noticement to the app itself. Since we also want nondevs to read it.

**Comment by TobiGr** [comment]
That's a good idea. I am working on the "What's New" dialog. When the app starts for the first time / after the update we can show a notice there. We could also try to add a notification for new blog posts.

**Comment by TheAssassin** [comment]
@TobiGr do we have an RSS feed that could be used for such stuff? If not, please think about making Jekyll generate one or, even better, have it generate a JSON feed (by far easier to parse).

**Comment by TobiGr** [comment]
@TheAssassin There are some plugins which can generate an RSS feed. But I'd rather implement a JSON generator too.

Btw. is there anybody with a 4k monitor out there? I think we should limit the website container and center it. Probably at more than 1800px. But I'd like to get some feedback first, because 4k displays can make trouble. 🙄

**Comment by TheAssassin** [comment]
@TobiGr there are such generators available already. Check out https://github.com/AppImage/appimage.github.io/ for example. It provides a JSON feed of all AppImages it knows about.

**Comment by wb9688** [comment]
@TobiGr: I've 1440p, but that isn't enough, right?

**Comment by TheAssassin** [comment]
@TobiGr well, actually, you should be able to add a rule to scale the website on huge screens. I think Bootstrap have a solution for this already.

**Comment by TobiGr** [comment]
> well, actually, you should be able to add a rule to scale the website on huge screens. I think Bootstrap have a solution for this already.

Bootstrap does that, that's right. I was a little unspecific. I meant, large screens. Our website has no limits for its width. I just checked it at university and I think it looks horrible xD

<hr>

As said in my last PR, I want to reduce the number of long texts and add more buttons. That's what I thought of. @theScrabi @TheAssassin and everyone else,  please tell me what you think.

# Quick info section

This section is visible to the viewer when he open the website. It is placed above the features. Here is every information a potential new user needs:

**Supported services**: quick summary what the services does; maybe information how the extractor it works.
**Downloads**: new features of the latest version / links to F-Droid or direct download from F-Droid

![img_20180226_210312](https://user-images.githubusercontent.com/17365767/36694256-1260de98-1b3e-11e8-8528-b26bf3986635.jpg)

# Rework donation container

With moving information about F-Droid to the info section, the second text box tells no important information. That's why - and because it wasn't really catchy - the donation button needs a different design. I didn't add any describing text to it yet, but I am not sure if it needs one. What do you think?
Our footer needs a rework too, as we have a couple of subsites now.

![footer_3](https://user-images.githubusercontent.com/17365767/36694264-16604dc6-1b3e-11e8-9cdd-6b396c5e4a60.png)

**Comment by theScrabi** [comment]
Btw could we close this thread and open up a new one, this one gets quite long.

**Comment by TobiGr** [comment]
Yes, there are a lot of images here :smile: 
I'll open a new o thread.
