### ISSUE TITLE
Links in the footer

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/website#24]
At the moment we have five links in the footer. We should discuss wether all of them are necessary. Here is a quick overview:

1. **Support**: If we want a support page we need to figure out how we want to help the people. I think that's more or less what the issue page on GitHub is doing right now. If we want to give them a little beginner guide, this can be done via an intro on the first launch of the app. We could provide the same information on a page. But as long as nothing like this exists this link is not needed.
2. **Privacy & Cookies**: This page is interesting for the user _if_ we collect any data about them. But so far no kind of cookie or tracker is used.
3. **Privacy Statement for Android**: I think this is really important. There is no possibility to view a privacy statement in the app (and I don't belive that one exists). Maybe we can write one along with [TeamNewPipe/NewPipe#572](https://github.com/TeamNewPipe/NewPipe/issues/572). Because the terms of use can be changed over time, the app must get the latest statement from the server. To be user-friendly we should provide the statement with a nice design at the website too.
4. **Security**: If I remember correctly, this link should refer to a site where we explain how NewPipe works and how it protects the users against tracking of Youtube / Google. This could be done in a blog post.
5. Copyright © NewPipe. All rights reserved. **Learn more.**: This is a link to the license of the website repository. As we do not have an imprint, this link is should be displayed on every page.

Besides that, we don't have a `fixed` navigation. That means, all links in the navigation bar are not visible for the user when he reaches the bottom of the page. That's why I'd like to provide at least a link to the blog in the footer.

**Comment by theScrabi** [comment]
About the support: Basicly thats github Issues, and that will keep being.

About that Privacy Statement for Android: We are sending data back to our servers, so we need one right :/

**Comment by wb9688** [comment]
@theScrabi: What data?

**Comment by theScrabi** [comment]
Bug reports via Mail. Doesn't that already count?

**Comment by TheAssassin** [comment]
I don't think so. It's no active data collection, and fully transparent to the user. We just create some part of the payload of the mail, but it's sent via the mail client, an external application. Nothing that could be classified as "private data" goes in it, except for the IP range (I'm not sure why @theScrabi introduced that). Furthermore, any user sending a mail to our service does (implicitly?) agree that we process the data he sends us. So I think we don't need a privacy note per se, although it's probably a good idea. We definitely have to investigate that further. We should be on the safe side, especially since @theScrabi, the server and I are located in the EU and thus are subject of the EU GDPR. We should make sure everything is alright.
