### ISSUE TITLE
 Make blog posts a little more well designed

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#40]
@TobiGr @TheAssassin the block looks awsome. I like it a lot!!!

However the blog posts could be made a little better. Maybe it was good to add a little design polecy on how to write these posts.
I asked a friend about a guide. He send me [this](https://www.chimpify.de/marketing/10-fehler-blog/), maybe it will help us.

Also I would like to have little images in the top right corner of every blog post. This image should summarize the blog post a little. This will make the post a little more interesting.

**Comment by TheAssassin** [comment]
You can't really compare this article with our type of blog, which is merely an informational instrument, providing mostly announcements, and not any content we'd like to make money of, as the article you linked to suggests.

**Comment by theScrabi** [comment]
Well... I think I can. I mean think of the people who are going to read this. Who will they be? It will be the people who are going to visit our website, and want to know what is going on. If you present them only block text it would put off.

You can not just put block text on the internet these days, and expect many people to read it.
And as far as I see this we want people to read our blog, otherwise why would we have it ;)

**Comment by TheAssassin** [comment]
Did you even read the blog texts? The articles I wrote aren't "mere blocks" or anything like that. Instead of setting up some weird policies, just proofread the articles people contribute, and suggest changes. That's also was less likely to put someone off who's trying to contribute in my opinion. Not everyone's good at writing, and any kind of policy won't necessarily increase the quality of the text or structure.

**Comment by theScrabi** [comment]
@TheAssassin 
> put someone off

I don't want to put you off. I just say that we should try to stick to a good style when writing blog posts ;)
